"""
Personal Data Analytics Portfolio - Task 2: Exploratory Data Analysis
Uses the dataset generated by Task 1.
"""

from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt

BASE = Path(__file__).resolve().parents[1]
INPUT = BASE / "Task1_Web_Scraping" / "data" / "books.csv"
OUT = Path(__file__).parent / "output"
OUT.mkdir(exist_ok=True)


def main():
    if not INPUT.exists():
        raise FileNotFoundError(
            "books.csv not found. Run Task1_Web_Scraping/scrape_books.py first."
        )

    df = pd.read_csv(INPUT)

    print("\n--- DATASET SHAPE ---")
    print(df.shape)

    print("\n--- FIRST 10 ROWS ---")
    print(df.head(10))

    print("\n--- DATA TYPES ---")
    print(df.dtypes)

    print("\n--- MISSING VALUES ---")
    print(df.isna().sum())

    print("\n--- DUPLICATES ---")
    print(df.duplicated().sum())

    print("\n--- SUMMARY STATISTICS ---")
    print(df.describe(numeric_only=True))

    print("\n--- ANSWERS TO KEY QUESTIONS ---")
    print("Average price:", round(df["price_gbp"].mean(), 2))
    print("Median price:", round(df["price_gbp"].median(), 2))
    print("Average rating:", round(df["rating"].mean(), 2))

    most_expensive = df.loc[df["price_gbp"].idxmax()]
    print("Most expensive book:", most_expensive["title"],
          "£", most_expensive["price_gbp"])

    print("\nBooks by rating:")
    print(df["rating"].value_counts().sort_index())

    # Outlier detection using IQR
    q1 = df["price_gbp"].quantile(0.25)
    q3 = df["price_gbp"].quantile(0.75)
    iqr = q3 - q1
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr
    outliers = df[(df["price_gbp"] < lower) | (df["price_gbp"] > upper)]

    print(f"\nPrice IQR bounds: {lower:.2f} to {upper:.2f}")
    print("Potential price outliers:", len(outliers))

    # Save a compact report
    report = pd.DataFrame({
        "metric": [
            "Rows", "Columns", "Average price (GBP)", "Median price (GBP)",
            "Average rating", "Duplicate rows", "Potential price outliers"
        ],
        "value": [
            len(df), len(df.columns), round(df["price_gbp"].mean(), 2),
            round(df["price_gbp"].median(), 2), round(df["rating"].mean(), 2),
            int(df.duplicated().sum()), len(outliers)
        ]
    })
    report.to_csv(OUT / "eda_summary.csv", index=False)

    # Histogram
    plt.figure(figsize=(8, 5))
    plt.hist(df["price_gbp"], bins=15)
    plt.title("Distribution of Book Prices")
    plt.xlabel("Price (GBP)")
    plt.ylabel("Number of Books")
    plt.tight_layout()
    plt.savefig(OUT / "price_distribution.png", dpi=150)
    plt.close()

    print(f"\nEDA summary and chart saved in: {OUT}")


if __name__ == "__main__":
    main()
